// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: variety.proto

public final class Variety {
  private Variety() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string name = 1;
    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // required string email = 2;
    /**
     * <code>required string email = 2;</code>
     */
    boolean hasEmail();
    /**
     * <code>required string email = 2;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>required string email = 2;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    // optional int32 logins = 3;
    /**
     * <code>optional int32 logins = 3;</code>
     */
    boolean hasLogins();
    /**
     * <code>optional int32 logins = 3;</code>
     */
    int getLogins();
  }
  /**
   * Protobuf type {@code User}
   */
  public static final class User extends
      com.google.protobuf.GeneratedMessage
      implements UserOrBuilder {
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private User(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final User defaultInstance;
    public static User getDefaultInstance() {
      return defaultInstance;
    }

    public User getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              email_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              logins_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Variety.internal_static_User_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Variety.internal_static_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Variety.User.class, Variety.User.Builder.class);
    }

    public static com.google.protobuf.Parser<User> PARSER =
        new com.google.protobuf.AbstractParser<User>() {
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string email = 2;
    public static final int EMAIL_FIELD_NUMBER = 2;
    private java.lang.Object email_;
    /**
     * <code>required string email = 2;</code>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string email = 2;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string email = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 logins = 3;
    public static final int LOGINS_FIELD_NUMBER = 3;
    private int logins_;
    /**
     * <code>optional int32 logins = 3;</code>
     */
    public boolean hasLogins() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 logins = 3;</code>
     */
    public int getLogins() {
      return logins_;
    }

    private void initFields() {
      name_ = "";
      email_ = "";
      logins_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEmail()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getEmailBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, logins_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getEmailBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, logins_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Variety.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Variety.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Variety.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Variety.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Variety.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Variety.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Variety.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Variety.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Variety.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Variety.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Variety.User prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Variety.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Variety.internal_static_User_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Variety.internal_static_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Variety.User.class, Variety.User.Builder.class);
      }

      // Construct using Variety.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        logins_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Variety.internal_static_User_descriptor;
      }

      public Variety.User getDefaultInstanceForType() {
        return Variety.User.getDefaultInstance();
      }

      public Variety.User build() {
        Variety.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Variety.User buildPartial() {
        Variety.User result = new Variety.User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.email_ = email_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.logins_ = logins_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Variety.User) {
          return mergeFrom((Variety.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Variety.User other) {
        if (other == Variety.User.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasEmail()) {
          bitField0_ |= 0x00000002;
          email_ = other.email_;
          onChanged();
        }
        if (other.hasLogins()) {
          setLogins(other.getLogins());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasEmail()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Variety.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Variety.User) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // required string email = 2;
      private java.lang.Object email_ = "";
      /**
       * <code>required string email = 2;</code>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string email = 2;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string email = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string email = 2;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string email = 2;</code>
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000002);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>required string email = 2;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        email_ = value;
        onChanged();
        return this;
      }

      // optional int32 logins = 3;
      private int logins_ ;
      /**
       * <code>optional int32 logins = 3;</code>
       */
      public boolean hasLogins() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 logins = 3;</code>
       */
      public int getLogins() {
        return logins_;
      }
      /**
       * <code>optional int32 logins = 3;</code>
       */
      public Builder setLogins(int value) {
        bitField0_ |= 0x00000004;
        logins_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 logins = 3;</code>
       */
      public Builder clearLogins() {
        bitField0_ = (bitField0_ & ~0x00000004);
        logins_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:User)
    }

    static {
      defaultInstance = new User(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:User)
  }

  public interface GroupOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .User users = 1;
    /**
     * <code>repeated .User users = 1;</code>
     */
    java.util.List<Variety.User> 
        getUsersList();
    /**
     * <code>repeated .User users = 1;</code>
     */
    Variety.User getUsers(int index);
    /**
     * <code>repeated .User users = 1;</code>
     */
    int getUsersCount();
    /**
     * <code>repeated .User users = 1;</code>
     */
    java.util.List<? extends Variety.UserOrBuilder> 
        getUsersOrBuilderList();
    /**
     * <code>repeated .User users = 1;</code>
     */
    Variety.UserOrBuilder getUsersOrBuilder(
        int index);

    // repeated .Group subgroups = 2;
    /**
     * <code>repeated .Group subgroups = 2;</code>
     */
    java.util.List<Variety.Group> 
        getSubgroupsList();
    /**
     * <code>repeated .Group subgroups = 2;</code>
     */
    Variety.Group getSubgroups(int index);
    /**
     * <code>repeated .Group subgroups = 2;</code>
     */
    int getSubgroupsCount();
    /**
     * <code>repeated .Group subgroups = 2;</code>
     */
    java.util.List<? extends Variety.GroupOrBuilder> 
        getSubgroupsOrBuilderList();
    /**
     * <code>repeated .Group subgroups = 2;</code>
     */
    Variety.GroupOrBuilder getSubgroupsOrBuilder(
        int index);

    // optional .Group.GroupType group_type = 3;
    /**
     * <code>optional .Group.GroupType group_type = 3;</code>
     */
    boolean hasGroupType();
    /**
     * <code>optional .Group.GroupType group_type = 3;</code>
     */
    Variety.Group.GroupType getGroupType();
  }
  /**
   * Protobuf type {@code Group}
   */
  public static final class Group extends
      com.google.protobuf.GeneratedMessage
      implements GroupOrBuilder {
    // Use Group.newBuilder() to construct.
    private Group(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Group(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Group defaultInstance;
    public static Group getDefaultInstance() {
      return defaultInstance;
    }

    public Group getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Group(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                users_ = new java.util.ArrayList<Variety.User>();
                mutable_bitField0_ |= 0x00000001;
              }
              users_.add(input.readMessage(Variety.User.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                subgroups_ = new java.util.ArrayList<Variety.Group>();
                mutable_bitField0_ |= 0x00000002;
              }
              subgroups_.add(input.readMessage(Variety.Group.PARSER, extensionRegistry));
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              Variety.Group.GroupType value = Variety.Group.GroupType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                groupType_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          users_ = java.util.Collections.unmodifiableList(users_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          subgroups_ = java.util.Collections.unmodifiableList(subgroups_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Variety.internal_static_Group_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Variety.internal_static_Group_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Variety.Group.class, Variety.Group.Builder.class);
    }

    public static com.google.protobuf.Parser<Group> PARSER =
        new com.google.protobuf.AbstractParser<Group>() {
      public Group parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Group(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Group> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code Group.GroupType}
     */
    public enum GroupType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Study = 1;</code>
       */
      Study(0, 1),
      /**
       * <code>Play = 2;</code>
       */
      Play(1, 2),
      ;

      /**
       * <code>Study = 1;</code>
       */
      public static final int Study_VALUE = 1;
      /**
       * <code>Play = 2;</code>
       */
      public static final int Play_VALUE = 2;


      public final int getNumber() { return value; }

      public static GroupType valueOf(int value) {
        switch (value) {
          case 1: return Study;
          case 2: return Play;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<GroupType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<GroupType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<GroupType>() {
              public GroupType findValueByNumber(int number) {
                return GroupType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Variety.Group.getDescriptor().getEnumTypes().get(0);
      }

      private static final GroupType[] VALUES = values();

      public static GroupType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private GroupType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Group.GroupType)
    }

    private int bitField0_;
    // repeated .User users = 1;
    public static final int USERS_FIELD_NUMBER = 1;
    private java.util.List<Variety.User> users_;
    /**
     * <code>repeated .User users = 1;</code>
     */
    public java.util.List<Variety.User> getUsersList() {
      return users_;
    }
    /**
     * <code>repeated .User users = 1;</code>
     */
    public java.util.List<? extends Variety.UserOrBuilder> 
        getUsersOrBuilderList() {
      return users_;
    }
    /**
     * <code>repeated .User users = 1;</code>
     */
    public int getUsersCount() {
      return users_.size();
    }
    /**
     * <code>repeated .User users = 1;</code>
     */
    public Variety.User getUsers(int index) {
      return users_.get(index);
    }
    /**
     * <code>repeated .User users = 1;</code>
     */
    public Variety.UserOrBuilder getUsersOrBuilder(
        int index) {
      return users_.get(index);
    }

    // repeated .Group subgroups = 2;
    public static final int SUBGROUPS_FIELD_NUMBER = 2;
    private java.util.List<Variety.Group> subgroups_;
    /**
     * <code>repeated .Group subgroups = 2;</code>
     */
    public java.util.List<Variety.Group> getSubgroupsList() {
      return subgroups_;
    }
    /**
     * <code>repeated .Group subgroups = 2;</code>
     */
    public java.util.List<? extends Variety.GroupOrBuilder> 
        getSubgroupsOrBuilderList() {
      return subgroups_;
    }
    /**
     * <code>repeated .Group subgroups = 2;</code>
     */
    public int getSubgroupsCount() {
      return subgroups_.size();
    }
    /**
     * <code>repeated .Group subgroups = 2;</code>
     */
    public Variety.Group getSubgroups(int index) {
      return subgroups_.get(index);
    }
    /**
     * <code>repeated .Group subgroups = 2;</code>
     */
    public Variety.GroupOrBuilder getSubgroupsOrBuilder(
        int index) {
      return subgroups_.get(index);
    }

    // optional .Group.GroupType group_type = 3;
    public static final int GROUP_TYPE_FIELD_NUMBER = 3;
    private Variety.Group.GroupType groupType_;
    /**
     * <code>optional .Group.GroupType group_type = 3;</code>
     */
    public boolean hasGroupType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .Group.GroupType group_type = 3;</code>
     */
    public Variety.Group.GroupType getGroupType() {
      return groupType_;
    }

    private void initFields() {
      users_ = java.util.Collections.emptyList();
      subgroups_ = java.util.Collections.emptyList();
      groupType_ = Variety.Group.GroupType.Study;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getUsersCount(); i++) {
        if (!getUsers(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getSubgroupsCount(); i++) {
        if (!getSubgroups(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < users_.size(); i++) {
        output.writeMessage(1, users_.get(i));
      }
      for (int i = 0; i < subgroups_.size(); i++) {
        output.writeMessage(2, subgroups_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(3, groupType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < users_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, users_.get(i));
      }
      for (int i = 0; i < subgroups_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, subgroups_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, groupType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Variety.Group parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Variety.Group parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Variety.Group parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Variety.Group parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Variety.Group parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Variety.Group parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Variety.Group parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Variety.Group parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Variety.Group parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Variety.Group parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Variety.Group prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Group}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Variety.GroupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Variety.internal_static_Group_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Variety.internal_static_Group_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Variety.Group.class, Variety.Group.Builder.class);
      }

      // Construct using Variety.Group.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUsersFieldBuilder();
          getSubgroupsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (usersBuilder_ == null) {
          users_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          usersBuilder_.clear();
        }
        if (subgroupsBuilder_ == null) {
          subgroups_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          subgroupsBuilder_.clear();
        }
        groupType_ = Variety.Group.GroupType.Study;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Variety.internal_static_Group_descriptor;
      }

      public Variety.Group getDefaultInstanceForType() {
        return Variety.Group.getDefaultInstance();
      }

      public Variety.Group build() {
        Variety.Group result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Variety.Group buildPartial() {
        Variety.Group result = new Variety.Group(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (usersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            users_ = java.util.Collections.unmodifiableList(users_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.users_ = users_;
        } else {
          result.users_ = usersBuilder_.build();
        }
        if (subgroupsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            subgroups_ = java.util.Collections.unmodifiableList(subgroups_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.subgroups_ = subgroups_;
        } else {
          result.subgroups_ = subgroupsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000001;
        }
        result.groupType_ = groupType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Variety.Group) {
          return mergeFrom((Variety.Group)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Variety.Group other) {
        if (other == Variety.Group.getDefaultInstance()) return this;
        if (usersBuilder_ == null) {
          if (!other.users_.isEmpty()) {
            if (users_.isEmpty()) {
              users_ = other.users_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureUsersIsMutable();
              users_.addAll(other.users_);
            }
            onChanged();
          }
        } else {
          if (!other.users_.isEmpty()) {
            if (usersBuilder_.isEmpty()) {
              usersBuilder_.dispose();
              usersBuilder_ = null;
              users_ = other.users_;
              bitField0_ = (bitField0_ & ~0x00000001);
              usersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getUsersFieldBuilder() : null;
            } else {
              usersBuilder_.addAllMessages(other.users_);
            }
          }
        }
        if (subgroupsBuilder_ == null) {
          if (!other.subgroups_.isEmpty()) {
            if (subgroups_.isEmpty()) {
              subgroups_ = other.subgroups_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureSubgroupsIsMutable();
              subgroups_.addAll(other.subgroups_);
            }
            onChanged();
          }
        } else {
          if (!other.subgroups_.isEmpty()) {
            if (subgroupsBuilder_.isEmpty()) {
              subgroupsBuilder_.dispose();
              subgroupsBuilder_ = null;
              subgroups_ = other.subgroups_;
              bitField0_ = (bitField0_ & ~0x00000002);
              subgroupsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSubgroupsFieldBuilder() : null;
            } else {
              subgroupsBuilder_.addAllMessages(other.subgroups_);
            }
          }
        }
        if (other.hasGroupType()) {
          setGroupType(other.getGroupType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getUsersCount(); i++) {
          if (!getUsers(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getSubgroupsCount(); i++) {
          if (!getSubgroups(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Variety.Group parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Variety.Group) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .User users = 1;
      private java.util.List<Variety.User> users_ =
        java.util.Collections.emptyList();
      private void ensureUsersIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          users_ = new java.util.ArrayList<Variety.User>(users_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Variety.User, Variety.User.Builder, Variety.UserOrBuilder> usersBuilder_;

      /**
       * <code>repeated .User users = 1;</code>
       */
      public java.util.List<Variety.User> getUsersList() {
        if (usersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(users_);
        } else {
          return usersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .User users = 1;</code>
       */
      public int getUsersCount() {
        if (usersBuilder_ == null) {
          return users_.size();
        } else {
          return usersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .User users = 1;</code>
       */
      public Variety.User getUsers(int index) {
        if (usersBuilder_ == null) {
          return users_.get(index);
        } else {
          return usersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .User users = 1;</code>
       */
      public Builder setUsers(
          int index, Variety.User value) {
        if (usersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUsersIsMutable();
          users_.set(index, value);
          onChanged();
        } else {
          usersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .User users = 1;</code>
       */
      public Builder setUsers(
          int index, Variety.User.Builder builderForValue) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          users_.set(index, builderForValue.build());
          onChanged();
        } else {
          usersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .User users = 1;</code>
       */
      public Builder addUsers(Variety.User value) {
        if (usersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUsersIsMutable();
          users_.add(value);
          onChanged();
        } else {
          usersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .User users = 1;</code>
       */
      public Builder addUsers(
          int index, Variety.User value) {
        if (usersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUsersIsMutable();
          users_.add(index, value);
          onChanged();
        } else {
          usersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .User users = 1;</code>
       */
      public Builder addUsers(
          Variety.User.Builder builderForValue) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          users_.add(builderForValue.build());
          onChanged();
        } else {
          usersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .User users = 1;</code>
       */
      public Builder addUsers(
          int index, Variety.User.Builder builderForValue) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          users_.add(index, builderForValue.build());
          onChanged();
        } else {
          usersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .User users = 1;</code>
       */
      public Builder addAllUsers(
          java.lang.Iterable<? extends Variety.User> values) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          super.addAll(values, users_);
          onChanged();
        } else {
          usersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .User users = 1;</code>
       */
      public Builder clearUsers() {
        if (usersBuilder_ == null) {
          users_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          usersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .User users = 1;</code>
       */
      public Builder removeUsers(int index) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          users_.remove(index);
          onChanged();
        } else {
          usersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .User users = 1;</code>
       */
      public Variety.User.Builder getUsersBuilder(
          int index) {
        return getUsersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .User users = 1;</code>
       */
      public Variety.UserOrBuilder getUsersOrBuilder(
          int index) {
        if (usersBuilder_ == null) {
          return users_.get(index);  } else {
          return usersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .User users = 1;</code>
       */
      public java.util.List<? extends Variety.UserOrBuilder> 
           getUsersOrBuilderList() {
        if (usersBuilder_ != null) {
          return usersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(users_);
        }
      }
      /**
       * <code>repeated .User users = 1;</code>
       */
      public Variety.User.Builder addUsersBuilder() {
        return getUsersFieldBuilder().addBuilder(
            Variety.User.getDefaultInstance());
      }
      /**
       * <code>repeated .User users = 1;</code>
       */
      public Variety.User.Builder addUsersBuilder(
          int index) {
        return getUsersFieldBuilder().addBuilder(
            index, Variety.User.getDefaultInstance());
      }
      /**
       * <code>repeated .User users = 1;</code>
       */
      public java.util.List<Variety.User.Builder> 
           getUsersBuilderList() {
        return getUsersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Variety.User, Variety.User.Builder, Variety.UserOrBuilder> 
          getUsersFieldBuilder() {
        if (usersBuilder_ == null) {
          usersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Variety.User, Variety.User.Builder, Variety.UserOrBuilder>(
                  users_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          users_ = null;
        }
        return usersBuilder_;
      }

      // repeated .Group subgroups = 2;
      private java.util.List<Variety.Group> subgroups_ =
        java.util.Collections.emptyList();
      private void ensureSubgroupsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          subgroups_ = new java.util.ArrayList<Variety.Group>(subgroups_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Variety.Group, Variety.Group.Builder, Variety.GroupOrBuilder> subgroupsBuilder_;

      /**
       * <code>repeated .Group subgroups = 2;</code>
       */
      public java.util.List<Variety.Group> getSubgroupsList() {
        if (subgroupsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(subgroups_);
        } else {
          return subgroupsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Group subgroups = 2;</code>
       */
      public int getSubgroupsCount() {
        if (subgroupsBuilder_ == null) {
          return subgroups_.size();
        } else {
          return subgroupsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Group subgroups = 2;</code>
       */
      public Variety.Group getSubgroups(int index) {
        if (subgroupsBuilder_ == null) {
          return subgroups_.get(index);
        } else {
          return subgroupsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Group subgroups = 2;</code>
       */
      public Builder setSubgroups(
          int index, Variety.Group value) {
        if (subgroupsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubgroupsIsMutable();
          subgroups_.set(index, value);
          onChanged();
        } else {
          subgroupsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Group subgroups = 2;</code>
       */
      public Builder setSubgroups(
          int index, Variety.Group.Builder builderForValue) {
        if (subgroupsBuilder_ == null) {
          ensureSubgroupsIsMutable();
          subgroups_.set(index, builderForValue.build());
          onChanged();
        } else {
          subgroupsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Group subgroups = 2;</code>
       */
      public Builder addSubgroups(Variety.Group value) {
        if (subgroupsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubgroupsIsMutable();
          subgroups_.add(value);
          onChanged();
        } else {
          subgroupsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Group subgroups = 2;</code>
       */
      public Builder addSubgroups(
          int index, Variety.Group value) {
        if (subgroupsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubgroupsIsMutable();
          subgroups_.add(index, value);
          onChanged();
        } else {
          subgroupsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Group subgroups = 2;</code>
       */
      public Builder addSubgroups(
          Variety.Group.Builder builderForValue) {
        if (subgroupsBuilder_ == null) {
          ensureSubgroupsIsMutable();
          subgroups_.add(builderForValue.build());
          onChanged();
        } else {
          subgroupsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Group subgroups = 2;</code>
       */
      public Builder addSubgroups(
          int index, Variety.Group.Builder builderForValue) {
        if (subgroupsBuilder_ == null) {
          ensureSubgroupsIsMutable();
          subgroups_.add(index, builderForValue.build());
          onChanged();
        } else {
          subgroupsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Group subgroups = 2;</code>
       */
      public Builder addAllSubgroups(
          java.lang.Iterable<? extends Variety.Group> values) {
        if (subgroupsBuilder_ == null) {
          ensureSubgroupsIsMutable();
          super.addAll(values, subgroups_);
          onChanged();
        } else {
          subgroupsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Group subgroups = 2;</code>
       */
      public Builder clearSubgroups() {
        if (subgroupsBuilder_ == null) {
          subgroups_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          subgroupsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Group subgroups = 2;</code>
       */
      public Builder removeSubgroups(int index) {
        if (subgroupsBuilder_ == null) {
          ensureSubgroupsIsMutable();
          subgroups_.remove(index);
          onChanged();
        } else {
          subgroupsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Group subgroups = 2;</code>
       */
      public Variety.Group.Builder getSubgroupsBuilder(
          int index) {
        return getSubgroupsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Group subgroups = 2;</code>
       */
      public Variety.GroupOrBuilder getSubgroupsOrBuilder(
          int index) {
        if (subgroupsBuilder_ == null) {
          return subgroups_.get(index);  } else {
          return subgroupsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Group subgroups = 2;</code>
       */
      public java.util.List<? extends Variety.GroupOrBuilder> 
           getSubgroupsOrBuilderList() {
        if (subgroupsBuilder_ != null) {
          return subgroupsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(subgroups_);
        }
      }
      /**
       * <code>repeated .Group subgroups = 2;</code>
       */
      public Variety.Group.Builder addSubgroupsBuilder() {
        return getSubgroupsFieldBuilder().addBuilder(
            Variety.Group.getDefaultInstance());
      }
      /**
       * <code>repeated .Group subgroups = 2;</code>
       */
      public Variety.Group.Builder addSubgroupsBuilder(
          int index) {
        return getSubgroupsFieldBuilder().addBuilder(
            index, Variety.Group.getDefaultInstance());
      }
      /**
       * <code>repeated .Group subgroups = 2;</code>
       */
      public java.util.List<Variety.Group.Builder> 
           getSubgroupsBuilderList() {
        return getSubgroupsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Variety.Group, Variety.Group.Builder, Variety.GroupOrBuilder> 
          getSubgroupsFieldBuilder() {
        if (subgroupsBuilder_ == null) {
          subgroupsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Variety.Group, Variety.Group.Builder, Variety.GroupOrBuilder>(
                  subgroups_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          subgroups_ = null;
        }
        return subgroupsBuilder_;
      }

      // optional .Group.GroupType group_type = 3;
      private Variety.Group.GroupType groupType_ = Variety.Group.GroupType.Study;
      /**
       * <code>optional .Group.GroupType group_type = 3;</code>
       */
      public boolean hasGroupType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .Group.GroupType group_type = 3;</code>
       */
      public Variety.Group.GroupType getGroupType() {
        return groupType_;
      }
      /**
       * <code>optional .Group.GroupType group_type = 3;</code>
       */
      public Builder setGroupType(Variety.Group.GroupType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        groupType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .Group.GroupType group_type = 3;</code>
       */
      public Builder clearGroupType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        groupType_ = Variety.Group.GroupType.Study;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Group)
    }

    static {
      defaultInstance = new Group(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Group)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_User_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Group_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Group_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rvariety.proto\"3\n\004User\022\014\n\004name\030\001 \002(\t\022\r\n" +
      "\005email\030\002 \002(\t\022\016\n\006logins\030\003 \001(\005\"\200\001\n\005Group\022\024" +
      "\n\005users\030\001 \003(\0132\005.User\022\031\n\tsubgroups\030\002 \003(\0132" +
      "\006.Group\022$\n\ngroup_type\030\003 \001(\0162\020.Group.Grou" +
      "pType\" \n\tGroupType\022\t\n\005Study\020\001\022\010\n\004Play\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_User_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_User_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_User_descriptor,
              new java.lang.String[] { "Name", "Email", "Logins", });
          internal_static_Group_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Group_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Group_descriptor,
              new java.lang.String[] { "Users", "Subgroups", "GroupType", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
